"""Add guest user and passport photo support

Revision ID: 869f0fbcf447
Revises: 
Create Date: 2024-11-14 06:54:39.380615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '869f0fbcf447'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_guest', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('passport_photo', sa.String(length=255), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.drop_column('passport_photo')
        batch_op.drop_column('is_guest')

    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.drop_column('paid_date')

    op.drop_table('monthly_transaction')
    # ### end Alembic commands ###
