"""Add guest user and passport photo support

Revision ID: 869f0fbcf447
Revises: 
Create Date: 2024-11-14 06:54:39.380615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '869f0fbcf447'
down_revision = None
branch_labels = None
depends_on = None


def _create_legacy_base_tables():
    """Fresh installs only.

    The very first version of the app created its tables with db.create_all(), so this migration
    (which only alters tables) had nothing to build on for a brand new database. When the
    original tables are missing we create them here, in the shape they had before this
    revision. A database that already has them (every existing install) is left alone.
    """
    op.create_table('user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=120), nullable=False),
        sa.Column('password_hash', sa.String(length=128), nullable=False),
        sa.Column('is_verified', sa.Boolean(), nullable=True),
        sa.Column('is_admin', sa.Boolean(), nullable=True),
        sa.Column('national_id', sa.String(length=20), nullable=False),
        sa.Column('account_number', sa.String(length=20), nullable=True),
        sa.Column('first_name', sa.String(length=50), nullable=False),
        sa.Column('last_name', sa.String(length=50), nullable=False),
        sa.Column('other_names', sa.String(length=50), nullable=True),
        sa.Column('date_of_birth', sa.Date(), nullable=False),
        sa.Column('occupation', sa.String(length=100), nullable=False),
        sa.Column('phone_number', sa.String(length=20), nullable=False),
        sa.Column('address', sa.String(length=200), nullable=False),
        sa.Column('city', sa.String(length=100), nullable=False),
        sa.Column('state', sa.String(length=100), nullable=False),
        sa.Column('country', sa.String(length=100), nullable=False),
        sa.Column('national_id_file', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('account_number'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('national_id'),
    )
    op.create_table('contribution',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('date', sa.DateTime(), nullable=True),
        sa.Column('contribution_type', sa.String(length=20), nullable=True),
        sa.Column('month', sa.String(length=7), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('loan',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('interest_rate', sa.Float(), nullable=True),
        sa.Column('total_amount', sa.Float(), nullable=True),
        sa.Column('amount_paid', sa.Float(), nullable=True),
        sa.Column('remaining_amount', sa.Float(), nullable=True),
        sa.Column('purpose', sa.String(length=200), nullable=False),
        sa.Column('guarantor_id', sa.Integer(), nullable=False),
        sa.Column('term', sa.Integer(), nullable=False),
        sa.Column('income', sa.Float(), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('application_date', sa.DateTime(), nullable=True),
        sa.Column('approval_date', sa.DateTime(), nullable=True),
        sa.Column('repayment_date', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['guarantor_id'], ['user.id']),
        sa.ForeignKeyConstraint(['user_id'], ['user.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('monthly_savings_target',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('target_amount', sa.Float(), nullable=False),
        sa.Column('start_date', sa.DateTime(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id']),
        sa.PrimaryKeyConstraint('id'),
    )


def upgrade():
    if 'user' not in sa.inspect(op.get_bind()).get_table_names():
        _create_legacy_base_tables()

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_guest', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('passport_photo', sa.String(length=255), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.drop_column('passport_photo')
        batch_op.drop_column('is_guest')

    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.drop_column('paid_date')

    op.drop_table('monthly_transaction')
    # ### end Alembic commands ###
