"""Add non-member guarantor fields to loan table

Revision ID: f930198d05db
Revises: c4e8a1d06f72
Create Date: 2026-09-26 11:03:32.596708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f930198d05db'
down_revision = 'c4e8a1d06f72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guarantor2_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('guarantor2_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('guarantor2_phone', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.drop_column('guarantor2_phone')
        batch_op.drop_column('guarantor2_email')
        batch_op.drop_column('guarantor2_name')

    # ### end Alembic commands ###
